require:
  - rubocop-rspec
  - rubocop-performance

# Style -----------------------------------------------------------------------

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Metrics ---------------------------------------------------------------------

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - Rakefile
    - lib/tasks/**/*.rake
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 15

# Layout ----------------------------------------------------------------------

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Naming/AccessorMethodName:
  Enabled: false

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    associations:
      - has_one
      - has_many
      - belongs_to
      - has_and_belongs_to_many
  ExpectedOrder:
      - module_inclusion
      - constants
      - associations
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

# RSpec -----------------------------------------------------------------------

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 22

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
